import glob
import os
import shutil
from pathlib import Path

from scientistgpt import Conversation, ScientistGPT
from scientistgpt.conversation.replay import save_actions_to_file
from scientistgpt.run_gpt_code.dynamic_code import module_dir
from tests.utils import record_or_replay_openai

ACTIONS_FILENAME = 'conversation_actions'


def run_scientist_gpt(data_description: str, goal_description: str, data_directory: str, output_directory: str):
    """
    Run ScientistGPT, and save all files generated by ScientistGPT to a specified output folder.
    """
    data_directory = Path(data_directory).absolute()
    output_directory = Path(output_directory).absolute()

    # Create empty output folder (delete if exists):
    if os.path.exists(output_directory):
        shutil.rmtree(output_directory)
    os.makedirs(output_directory)

    runner = ScientistGPT(data_description=data_description, goal_description=goal_description)

    @record_or_replay_openai
    def run():
        runner.run_all()

    absolute_home_path = Path().absolute()

    # we run in the data folder, so that chatgpt finds our files:
    os.chdir(data_directory)
    run()
    os.chdir(absolute_home_path)

    save_all_files_to_output_folder(output_directory, data_directory)


def view_saved_conversation(filename: str):
    Conversation.from_file(filename).print_all_messages()


def save_all_files_to_output_folder(output_directory, absolute_data_path):
    """
    Save all files generated by ScientistGPT to a specified output folder.
    """
    # Save conversation to text file:
    save_actions_to_file(output_directory / ACTIONS_FILENAME)

    # Move all gpt analysis result files to output folder:
    for file in glob.glob(str(absolute_data_path / (ScientistGPT.gpt_script_filename + '*.txt'))):
        shutil.move(file, output_directory)

    # Move all gpt analysis scripts to output folder:
    for file in glob.glob(str(Path(module_dir) / (ScientistGPT.gpt_script_filename + '*.py'))):
        shutil.move(file, output_directory)

    # Move all gpt generated plots to output folder:
    for file in glob.glob(str(absolute_data_path / '*.png')):
        shutil.move(file, output_directory)

    # TODO: this one is risky cs it might move our own data files (if they have .txt extension)
    # Move gpt generated txt files to output folder:
    for file in glob.glob(str(absolute_data_path / '*.txt')):
        shutil.move(file, output_directory)
