name: CI

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update && \
          sudo apt-get install -y wget

          wget https://github.com/jgm/pandoc/releases/download/3.6.2/pandoc-3.6.2-1-amd64.deb
          sudo dpkg -i pandoc-3.6.2-1-amd64.deb
          sudo apt-get install -f -y

          sudo apt-get install -y --no-install-recommends \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-fonts-recommended \
          libgl1 \
          libegl1 \
          libxkbcommon-x11-0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package
        run: |
          pip install .

      - name: Run tests
        run: pytest tests/
